# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Provider Shared Configuration
  config.ssh.insert_key = false


  # Virtualbox Provider Specific Configuration
  config.vm.provider "virtualbox" do |v|
    v.name = "vagrant-ubuntu2210"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "ubuntu2210" do |ubuntu2210|
    # VM Shared Configuration
    ubuntu2210.vm.box = "maroskukan/ubuntu2210"
    ubuntu2210.vm.hostname = "ubuntu2210"

    # Virtualbox VM Specific Configuration
    ubuntu2210.vm.provider 'virtualbox' do |v, override|
      override.vm.box = "file://builds/ubuntu2210-virtualbox.box"
      override.vm.synced_folder ".", "/vagrant", disabled: true
    end
  end

  # VM Shared Provisioning
  config.vm.provision "shell", inline: "cat /etc/os-release"
end
